# Generated by Django 5.1.5 on 2025-07-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_transaction_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank/UPI')], default='Cash', max_length=10),
            preserve_default=False,
        ),
    ]
